# This is a build configuration for clang format
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: alabate/clang-format

pipelines:
  custom:
    clang-format-check:
      - step:
          script:
            - find . -name \*.h -exec clang-format -i {} \;
            - find . -name \*.cc -exec clang-format -i {} \;
            - git diff
            - git diff-files --quiet
          